### ISSUE TITLE
Markdown renderer can't handle multiple-line code samples in lists.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/workbox-microsite#10]
The source that produced this is [here](https://github.com/GoogleChrome/workbox-microsite/blob/docs/src/get-started/gulp.md).

![rendered](https://cloud.githubusercontent.com/assets/8204171/25981015/6b77df0a-3687-11e7-9be0-89e80b0cd687.png)

**Comment by gauntface** [comment]
This is malformed markdown.

To have something considered as part of the list item you need to indent by 4 spaces. Doing this fixes your problem.

Also worth calling out there is a mix of tabs and spaces that can upset all of this as well.

The following works:

```
---
layout: page
title: Get Started > Gulp
---

# Gulp

1. [Install Node.js](https://nodejs.org/en/).
1. Install the module with NPM.

    ```
    npm install --save-dev sw-build
    ```

1. Require `sw-build` in your build script.

    ```
    const swBuild = require('sw-build');
    ```

1. Add the following to your `gulpfile.js`:

    ```
    gulp.task('build', () => {
      const swBuild = require('sw-build');
      return swBuild.generateSW({
        rootDirectory: './build/',
        swDest: './build/sw.js',
        globPatterns: ['**\/*.{html,js,css}'],
        globIgnores: ['admin.html'],
        templatedUrls: {
          '/shell': ['shell.hbs', 'main.css', 'shell.css'],
        },
      })
      .then(() => {
        console.log('Service worker generated.');
      })
      .catch((err) => {
        console.log('[ERROR] This happened: ' + err);
      });
    })
    ```
```

**Comment by jpmedley** [comment]
My link may be out of date, but I tried every variation I could think of before opening this ticket.

**Comment by gauntface** [comment]
Do you want me to commit the fix to your doc branch?

**Comment by jpmedley** [comment]
Please. If you know something I've overlooked...

Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by jpmedley** [comment]
No joy.

![wmqkhcu5dgc](https://cloud.githubusercontent.com/assets/8204171/26008437/a4e39be0-36f9-11e7-85c2-ab2553963703.png)

**Comment by jpmedley** [comment]
@gauntface FYI

**Comment by gauntface** [comment]
My view from docs branch right now.

Did you git pull, and ctrl + shift + r?

![screenshot from 2017-05-12 10 03 00](https://cloud.githubusercontent.com/assets/139760/26008579/3c12d17a-36fa-11e7-91c4-91aff2eaa4e5.png)

**Comment by jpmedley** [comment]
Doesn't work. Neither does deleting node_modules/ and reinstalling.

**Comment by gauntface** [comment]
Joe updated and I believe got it work - travis and my local thing seemed fine with changes above.
