### ISSUE TITLE
[Overview] the injectManifest() example is not found

### ISSUE THREAD

**Issue by atikenny** [GoogleChrome/workbox-microsite#110]
When I navigate to: [Workbox overview page](https://developers.google.com/web/tools/workbox/overview) and I click on the injectManifest() link above the Feedback section it navigates to a 404 page.
![inject-manifest-link](https://user-images.githubusercontent.com/6061509/32283458-43e7579a-bf1c-11e7-8b12-dd4542200cd2.png)

**Comment by jeffposnick** [comment]
See https://github.com/google/WebFundamentals/pull/5272
