### ISSUE TITLE
Code sample boxes need to align with surrounding text.

### ISSUE THREAD

**Issue by jpmedley** [GoogleChrome/workbox-microsite#14]
This is one instance where the text doesn't need to align.

![v1ns3u3zebn](https://cloud.githubusercontent.com/assets/8204171/26006149/403c703a-36f0-11e7-8619-4c5f274acc93.png)

**Comment by gauntface** [comment]
Sorry the title and the explanation in the issue seem contradictory. What would you like?

**Comment by jpmedley** [comment]
The box around the code needs to not bump out.

**Comment by gauntface** [comment]
This was missing original design from Addy - made it stretch out on index.
