### ISSUE TITLE
Remove jekyll-github-metadata?

### ISSUE THREAD

**Issue by jeffposnick** [GoogleChrome/workbox-microsite#29]
@gauntface, do we need `gems: ['jekyll-github-metadata']` in our [`_config.yml`](https://github.com/GoogleChrome/workbox-microsite/blob/master/src/_config.yml#L7)? If not, I'll remove it. It leads to failed metadata requests like the following after a few rebuilds:

```sh
GitHub Metadata: GET https://api.github.com/repos/GoogleChrome/workbox-microsite: 403 - API rate limit exceeded for 108.46.224.107. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting
```

**Comment by gauntface** [comment]
At the moment it's still refernced for things like taglines etc. but happy to remove if we add some simple backup text for description etc.

**Comment by jeffposnick** [comment]
Fine with keeping it given that it's actually being used.

**Comment by gauntface** [comment]
I think it's a good idea to remove at this point. I don't see this repo getting much T.L.C compared to workbox, so relying on it for content may not be the best idea.
