### ISSUE TITLE
Refresh landing page

### ISSUE THREAD

**Issue by addyosmani** [GoogleChrome/workbox-microsite#6]
Here's my first take at a rethink of the landing page content after our meeting:

![redesign](https://cloud.githubusercontent.com/assets/110953/25927083/2249442a-35a8-11e7-81dc-c57440b67ca3.png)

Focus less on the text (we can easily change that). I'd like to figure out if folks feel a layout like this or one like it would be more useful than what we have now.

We could easily expand the later sections to include more features/breakdowns. I kind of love how clean the http://babeljs.io/ site is and tried to draw some inspiration from it.

Shared the Sketch file for my silly attempt with @gauntface

**Comment by addyosmani** [comment]
@jpmedley and I just had a call about the homepage. Agreed on a few quick amendments:

- Rather than having a separate getting started page, the above (homepage) is effectively the getting started. That top-level menu item would just take you to it.

- The installation text becomes 'Getting Started'

We're still noodling on how best to get folks to be aware that there's reference docs available for the lower level packages. Whether those should be somehow represented lower down in the homepage or otherwise.

**Comment by jeffposnick** [comment]
A few nits:

- "A JavaScript Library for Progressive Web Apps" might give the wrong impression. Could we consider either "A JavaScript Framework for Progressive Web Apps" or "JavaScript Libraries for Progressive Web Apps" to emphasize that there's more to Workbox than a single library.

- If we wanted to show a really low-friction getting started snippet, we can go with

```js
importScripts('https://unpkg.com/workbox-sw@1.0.0');
```

- The "Easy Runtime Caching" section naming is a little odd, as I normally make the distinction between precaching (which you're showing) and runtime caching. Maybe call it "Easy Precaching"? `cacheRevisionedAssets()` has been renamed `precache()`. I'd also feel better if we could include a comment above that line saying that `workbox-build` will generate the list of files for you.

- In "Comprehensive caching strategies", "Generic fallback" isn't currently a caching strategy that we support (see https://github.com/GoogleChrome/sw-helpers/issues/438)

- There are various `sw` prefixes that I'm sure you were already planning on scrubbing.

**Comment by addyosmani** [comment]
> JavaScript Libraries for Progressive Web Apps

👍 

>

```importScripts('https://unpkg.com/workbox-sw@1.0.0');```

(although we should probably show it being used to do something too)

👍 

> "Easy Precaching"

That works for me.

> "Generic fallback" isn't currently a caching strategy that we support

Thanks for catching. I was trying to mostly do a super quick prototype based on what was in Jake's article assuming we'd match what we currently support when properly doing it.

> Prefixes

Yep. Let's change those to reflect reality :)

**Comment by jpmedley** [comment]
Regarding point one, I support ""JavaScript Libraries for Progressive Web Apps". Everything else +1.

**Comment by jpmedley** [comment]
@addyosmani @gauntface 

The new landing page looks good, but it doesn't follow everything in the discussion after Addy's image.

**Comment by addyosmani** [comment]
Morning folks 🌞 Great work so far.

As a P0 I would like us to focus next on getting the pages we're linking to from the homepage done first: #11, #12, #13 etc. At this point we need to rally around getting clear guidance for those up as soon as we can. A pretty homepage is great but less useful if the docs it aims to provide are 404s :)

@jpmedley Agreed with many of the points we discussed yesterday. Let's try to capture some of them here (marking as P1/2). As time is getting close I'm punting further homepage polish changes to early next week (or until at least the above three are up).
