### ISSUE TITLE
Implement pretty anchors

### ISSUE THREAD

**Issue by kaycebasques** [GoogleChrome/workbox-microsite#84]
In DevSite, I can just use the following syntax to define an explicit anchor for each section:

    ## Name of section {: #name }

And then you link to that section via `https://example.com/page#name`.

Jekyll just auto-generates section anchors from the text, which often creates really ugly and long anchors. Also, **if you change the text, the anchor fragment is no longer valid**. This is a big problem for me, because I do change the text often, and I often link directly to sections for maximum usability

**Comment by gauntface** [comment]
Does the above not work at the moment?

**Comment by kaycebasques** [comment]
No, it does not

**Comment by gauntface** [comment]
Just looked into this and you need to add a new line to do this

```
## Name of section
{: #name }
```
